#!/bin/bash

# Check if the current branch is 'master' or 'main'
current_branch=$(git symbolic-ref --short HEAD)
if [[ "$current_branch" != "main" && "$current_branch" != "master" ]]; then
  echo "Error: You must be on the 'main' or 'master' branch to run this script."
  echo "Switch branches and try again."
  exit 1
fi

echo "Pruning remote branches..."
git remote prune origin > /dev/null

remote_branches=$(git branch -r | grep -v master | grep -v main | sed "s/origin\///")
local_branches=$(git branch | grep -v master | grep -v main)

echo "Cleaning up local branches..."
echo

for local_branch in $local_branches; do
  # Check if the remote branch exists locally
  if ! echo "$remote_branches" | grep -qw "$local_branch"; then
    # Confirm deletion
    read -p "Do you want to delete the local branch '$local_branch'? (y/n): " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
      # If the use confirms, delete the local branch
      echo "Deleting local branch: $local_branch"
      git branch -D "$local_branch"
    else
      echo "Skipping deletion of branch: $local_branch"
    fi

    echo
  fi
done

echo "Done!"
